# Generated by Django 3.1.4 on 2021-01-06 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bulararaba',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('veika_e_vakayacori', models.CharField(max_length=255)),
                ('gauna_vakayacori_kina', models.TextField(max_length=50)),
                ('vakamacala_tale_eso', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Veivakalotutaki',
            },
        ),
        migrations.CreateModel(
            name='Lewenilotu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('yaca_ni_vuvale', models.CharField(max_length=255)),
                ('yacana', models.CharField(max_length=255)),
                ('tiki_ni_siganisucu', models.DateField(max_length=255)),
                ('tagane_se_yalewa', models.CharField(choices=[('Tgn', 'Tagane'), ('Ylw', 'Yalewa')], max_length=50)),
                ('phone_contact', models.CharField(max_length=255)),
                ('email_contact', models.CharField(max_length=255)),
                ('Adress', models.TextField(max_length=255)),
                ('tutu_vakalotu', models.CharField(choices=[('sigadina', 'Siga Dina'), ('sigatuberi', 'Siga Tuberi'), ('lwnvks', 'Leweni Vavakoso')], max_length=50)),
                ('tavi_vakalotu', models.CharField(choices=[('talcg', 'Talatala Vakacegu'), ('talyc', 'Talata Yaco'), ('taltv', 'Talatala Vakatovolei'), ('vktwcg', 'Vakatawa Vakacegu'), ('vktwyc', 'Vakatawa Yaco'), ('vktwtv', 'Vakatawa Vakatovolei'), ('dvnyc', 'Dauvunau Yaco'), ('dvntv', 'Dauvunau Vakatovolei'), ('msyc', 'Masumasu Yaco'), ('mstv', 'Masumasu Vakatovolei'), ('lwnvk', 'Leweni Vavakoso')], max_length=50)),
                ('vuli_keina_cakacaka', models.TextField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Lewenilotu',
            },
        ),
        migrations.CreateModel(
            name='Valenilotu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('yaca_ni_valenilotu', models.CharField(max_length=255)),
                ('yaca_ni_vakatawa', models.CharField(max_length=255)),
                ('vukevuke_ni_vakatawa', models.CharField(max_length=255)),
                ('tuirara', models.CharField(max_length=255)),
                ('vukevuke_ni_tuirara', models.CharField(max_length=255)),
                ('vunivola', models.CharField(max_length=255)),
                ('dauniyau', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone_contact', models.CharField(max_length=255)),
                ('vakamacala_tale_eso', models.TextField(max_length=255)),
                ('lewenilotu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.lewenilotu')),
            ],
            options={
                'verbose_name_plural': 'Valenilotu',
            },
        ),
        migrations.CreateModel(
            name='Veivakalotutaki',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('yacani_program', models.CharField(max_length=255)),
                ('gauna_vakayacori_kina', models.TextField(max_length=50)),
                ('vakamacala_tale_eso', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Veivakalotutaki',
            },
        ),
        migrations.CreateModel(
            name='Veitosoyaki',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('yacana', models.CharField(max_length=255)),
                ('toki', models.CharField(choices=[('tm', 'Toki Mai'), ('ty', 'Toki Yani')], max_length=50)),
                ('siga_e_yaco_kina', models.DateField(max_length=50)),
                ('vola', models.FileField(blank=True, null=True, upload_to='documents/veitosoyaki/%Y/%m/%d/')),
                ('vakamacala_tale_eso', models.TextField(max_length=255)),
                ('lewenilotu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.lewenilotu')),
            ],
            options={
                'verbose_name_plural': 'Veitosoyaki',
            },
        ),
        migrations.CreateModel(
            name='Veitokani',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('yaca_ni_veitokani', models.CharField(max_length=255)),
                ('liuliu_ni_veitokani', models.CharField(max_length=255)),
                ('vunivola_ni_veitokani', models.CharField(max_length=255)),
                ('dauniyau_ni_veitokani', models.CharField(max_length=255)),
                ('levu_ni_lavo_bula', models.CharField(max_length=255)),
                ('veika_dau_qaravi', models.TextField(max_length=255)),
                ('vakamacala_tale_eso', models.TextField(max_length=255)),
                ('lewenilotu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.lewenilotu')),
                ('valeninilotu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.valenilotu')),
            ],
            options={
                'verbose_name_plural': 'Veitokani',
            },
        ),
        migrations.CreateModel(
            name='Matasiga',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('yaca_ni_matasiga', models.CharField(max_length=255)),
                ('liuliu_ni_matasiga', models.CharField(max_length=255)),
                ('vanua_dau_soqoni_kina', models.TextField(max_length=255)),
                ('veika_dau_qaravi', models.TextField(max_length=255)),
                ('vakamacala_tale_eso', models.TextField(max_length=255)),
                ('lewenilotu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.lewenilotu')),
                ('valeninilotu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.valenilotu')),
            ],
            options={
                'verbose_name_plural': 'Matasiga',
            },
        ),
        migrations.AddField(
            model_name='lewenilotu',
            name='matasiga_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.matasiga'),
        ),
        migrations.AddField(
            model_name='lewenilotu',
            name='valenilotu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.valenilotu'),
        ),
        migrations.AddField(
            model_name='lewenilotu',
            name='veitokani_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.veitokani'),
        ),
    ]
