# Generated by Django 3.1.4 on 2021-01-07 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lewenilotu',
            old_name='yacana',
            new_name='lewenilotu',
        ),
        migrations.RenameField(
            model_name='matasiga',
            old_name='yaca_ni_matasiga',
            new_name='matasiga',
        ),
        migrations.RenameField(
            model_name='matasiga',
            old_name='valeninilotu_id',
            new_name='valeninilotu',
        ),
        migrations.RenameField(
            model_name='valenilotu',
            old_name='yaca_ni_valenilotu',
            new_name='valenilotu',
        ),
        migrations.RenameField(
            model_name='veitokani',
            old_name='valeninilotu_id',
            new_name='valeninilotu',
        ),
        migrations.RenameField(
            model_name='veitokani',
            old_name='yaca_ni_veitokani',
            new_name='veitokani',
        ),
        migrations.RenameField(
            model_name='veitosoyaki',
            old_name='lewenilotu_id',
            new_name='lewenilotu',
        ),
        migrations.RemoveField(
            model_name='lewenilotu',
            name='matasiga_id',
        ),
        migrations.RemoveField(
            model_name='lewenilotu',
            name='valenilotu_id',
        ),
        migrations.RemoveField(
            model_name='lewenilotu',
            name='veitokani_id',
        ),
        migrations.RemoveField(
            model_name='matasiga',
            name='lewenilotu_id',
        ),
        migrations.RemoveField(
            model_name='valenilotu',
            name='lewenilotu_id',
        ),
        migrations.RemoveField(
            model_name='veitokani',
            name='lewenilotu_id',
        ),
        migrations.AddField(
            model_name='lewenilotu',
            name='matasiga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.matasiga'),
        ),
        migrations.AddField(
            model_name='lewenilotu',
            name='valenilotu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.valenilotu'),
        ),
        migrations.AddField(
            model_name='lewenilotu',
            name='veitokani',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.veitokani'),
        ),
        migrations.AlterField(
            model_name='lewenilotu',
            name='tavi_vakalotu',
            field=models.CharField(choices=[('talcg', 'Talatala Vakacegu'), ('talyc', 'Talata Yaco'), ('taltv', 'Talatala Vakatovolei'), ('vktwcg', 'Vakatawa Vakacegu'), ('vktwyc', 'Vakatawa Yaco'), ('vktwtv', 'Vakatawa Vakatovolei'), ('dvnyc', 'Dauvunau Yaco'), ('dvntv', 'Dauvunau Vakatovolei'), ('dcms', 'Daucaka Masumasu'), ('lwnvk', 'Leweni Vavakoso')], max_length=50),
        ),
    ]
