# Generated by Django 3.1.4 on 2021-01-07 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210108_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulararaba',
            options={'verbose_name_plural': 'Bula Raraba'},
        ),
        migrations.RenameField(
            model_name='matasiga',
            old_name='valeninilotu',
            new_name='valenilotu',
        ),
        migrations.RenameField(
            model_name='veitokani',
            old_name='valeninilotu',
            new_name='valenilotu',
        ),
    ]
